// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PackManagementSystem.Context;

namespace PackManagementSystem.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20220312163620_intialmigration")]
    partial class intialmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("PackManagementSystem.Entities.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Firstname")
                        .HasColumnType("text");

                    b.Property<string>("Lastname")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("PackManagementSystem.Entities.Driver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<DateTime>("Dob")
                        .HasColumnType("datetime");

                    b.Property<string>("DriverId")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Firstname")
                        .HasColumnType("text");

                    b.Property<string>("Lastname")
                        .HasColumnType("text");

                    b.Property<int>("ParkId")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ParkId");

                    b.ToTable("Drivers");
                });

            modelBuilder.Entity("PackManagementSystem.Entities.Motor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CarReg")
                        .HasColumnType("text");

                    b.Property<string>("CarType")
                        .HasColumnType("text");

                    b.Property<string>("Carname")
                        .HasColumnType("text");

                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.Property<int>("NoOfSeater")
                        .HasColumnType("int");

                    b.Property<int>("ParkId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("ParkId");

                    b.ToTable("Motors");
                });

            modelBuilder.Entity("PackManagementSystem.Entities.Park", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<double>("Price")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("Parks");
                });

            modelBuilder.Entity("PackManagementSystem.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("Amount")
                        .HasColumnType("double");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime");

                    b.Property<int>("MotorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime");

                    b.Property<int>("PaymentPeriod")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MotorId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("PackManagementSystem.Entities.Staff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<DateTime>("Dob")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Firstname")
                        .HasColumnType("text");

                    b.Property<string>("Lastname")
                        .HasColumnType("text");

                    b.Property<int>("PackId")
                        .HasColumnType("int");

                    b.Property<int?>("ParkId")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("RegNum")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ParkId");

                    b.ToTable("Staffs");
                });

            modelBuilder.Entity("PackManagementSystem.Entities.Driver", b =>
                {
                    b.HasOne("PackManagementSystem.Entities.Park", "Park")
                        .WithMany("Drivers")
                        .HasForeignKey("ParkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Park");
                });

            modelBuilder.Entity("PackManagementSystem.Entities.Motor", b =>
                {
                    b.HasOne("PackManagementSystem.Entities.Driver", "Driver")
                        .WithMany("Motors")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PackManagementSystem.Entities.Park", "Park")
                        .WithMany("Motors")
                        .HasForeignKey("ParkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("Park");
                });

            modelBuilder.Entity("PackManagementSystem.Entities.Payment", b =>
                {
                    b.HasOne("PackManagementSystem.Entities.Motor", "Motor")
                        .WithMany("Payments")
                        .HasForeignKey("MotorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Motor");
                });

            modelBuilder.Entity("PackManagementSystem.Entities.Staff", b =>
                {
                    b.HasOne("PackManagementSystem.Entities.Park", "Park")
                        .WithMany("Staffs")
                        .HasForeignKey("ParkId");

                    b.Navigation("Park");
                });

            modelBuilder.Entity("PackManagementSystem.Entities.Driver", b =>
                {
                    b.Navigation("Motors");
                });

            modelBuilder.Entity("PackManagementSystem.Entities.Motor", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("PackManagementSystem.Entities.Park", b =>
                {
                    b.Navigation("Drivers");

                    b.Navigation("Motors");

                    b.Navigation("Staffs");
                });
#pragma warning restore 612, 618
        }
    }
}
